// Knowledge base for the EP support agent.
// Source: "EP Support KB" Google Sheet, Answers tab (rows A01–A24), copied 2026-10-06.
// Update this file (or ask Claude to resync) when the sheet changes.

export const KB = [
  { id: "A01", topic: "Access", ask: "Bought a course but never got login details / can't find my course.",
    answer: "Login details were emailed at sign-up with the subject \"IMPORTANT: Your Login Details to Embodied Philosophy\". Returning customers don't get new details: they sign in with their existing account. Sign in at https://school.embodiedphilosophy.com, open My Library and click See All to see everything they own. If they've forgotten their password, they can use the \"Forgot password\" link on the sign-in page.",
    handoff: "No purchase found under their email, or the course is still missing from My Library after signing in." },
  { id: "A02", topic: "Access", ask: "Paid but the course isn't in My Library.",
    answer: "Sometimes a purchase doesn't attach to the account correctly. Ichha can check the order and add it by hand.",
    handoff: "Always: collect the email used at checkout and order number if they have it." },
  { id: "A03", topic: "Access", ask: "Where are the bonus modules?",
    answer: "Bonus modules are added with the course. In My Library, click See All to view everything, including bonuses.",
    handoff: "They still can't see them after signing in." },
  { id: "A04", topic: "Access", ask: "Bought with a different email; move courses to main account.",
    answer: "Ichha can move purchases to the email they use.",
    handoff: "Always: collect both email addresses." },
  { id: "A05", topic: "Access", ask: "Do I keep access forever? Do I need a membership?",
    answer: "Single course purchases include lifetime access. They're a one-time payment, not a subscription, and no membership is needed to keep watching.",
    handoff: "They were charged again after a one-time purchase." },
  { id: "A06", topic: "Recordings", ask: "Will the live session be recorded? I missed it / left early.",
    answer: "Yes. Live sessions are recorded and the replay is added to the course in My Library, with lifetime access. Registered people sign in and open the course to watch it.",
    handoff: "They registered but the replay isn't showing." },
  { id: "A07", topic: "Recordings", ask: "Can I buy the recording of a past event?",
    answer: "Yes. Most live workshops can still be purchased as a recording from the event's enrollment page on enroll.embodiedphilosophy.com.",
    handoff: "They can't find the replay page for that event." },
  { id: "A08", topic: "Events", ask: "What time is the session in my time zone? Where's the Zoom link?",
    answer: "All event times are listed in Eastern Time (ET). Local time can be checked at https://www.timeanddate.com/worldclock/converter.html. The Zoom link is in the registration email and on the course page.",
    handoff: "They can't find the link and the session is starting soon." },
  { id: "A09", topic: "Refunds", ask: "I'd like a refund.",
    answer: "Individual courses and certificate programs can be refunded within 30 days of purchase. Memberships (monthly or annual, Wisdom School, Sādhana School, Meditation Pass) are NOT refundable, including the first charge after a free trial; members can cancel anytime before their next charge. You never issue refunds yourself.",
    handoff: "A course or certificate program bought within 30 days, or the situation seems unusual (technical problem, hardship, a mistake on our side)." },
  { id: "A10", topic: "Refunds", ask: "Charged twice / charged after I cancelled.",
    answer: "Apologise; Ichha will check the charges and refund anything duplicated.",
    handoff: "Always: collect the email used and the date/amount of the charge." },
  { id: "A11", topic: "Cancellations", ask: "Please cancel my subscription.",
    answer: "Members can cancel anytime and won't be charged again. Memberships aren't refunded, so cancelling before the next charge date avoids another payment. Ichha cancels and confirms. Only if they describe financial hardship, mention that Ichha can pause the membership for a few months instead.",
    handoff: "Always: collect email and which membership." },
  { id: "A12", topic: "Discounts", ask: "Do you offer scholarships or discounts? I can't afford it.",
    answer: "Only when the visitor asks for a discount: offer code 26Scholar25 (25% off at checkout) for general requests, alumni and replays. If they mention financial hardship or living in a lower-income country, offer 26Scholar50 (50% off) instead. Codes apply at checkout for courses and workshops.",
    handoff: "They ask for more than 50% off, a free place, or a discount on a membership renewal." },
  { id: "A13", topic: "Certificates", ask: "Will I get a certificate? CE hours?",
    answer: "Certificates are issued for certificate programs only. Regular courses and workshops don't include a certificate, but on completion EP can send an email confirming completion. Most courses count toward Yoga Alliance non-contact continuing education hours.",
    handoff: "They need their certificate, or want CE hours confirmed for a specific course." },
  { id: "A14", topic: "Materials", ask: "Where are the slides, readings or recommended texts?",
    answer: "Course materials such as slides and study guides are on the course page in My Library. Recommended texts are listed in the course's welcome email.",
    handoff: "The materials are missing from the course." },
  { id: "A15", topic: "Materials", ask: "Can I download the videos?",
    answer: "To protect teachers' work, videos can't be downloaded, but they can be streamed anytime with lifetime access.",
    handoff: "" },
  { id: "A16", topic: "Memberships", ask: "What's included in Wisdom School? How much?",
    answer: "Wisdom School includes the year's live programming (weekly meditation, monthly lectures, quarterly workshops) for $297/year. Wisdom School Plus adds learning pathways, the curated archive and certificate programs for $497/year. Both have monthly options and a 7-day free trial. Enroll: https://enroll.embodiedphilosophy.com/wisdom-school",
    handoff: "Pricing exceptions or renewal discounts." },
  { id: "A17", topic: "Memberships", ask: "Tell me about Sādhana School.",
    answer: "Sādhana School 2026–27 is a year of study in Pratyabhijñā philosophy and rasa theory. Orientation is October 18 and classes begin October 21; every session is recorded. $1,797 for the year or $497 per semester. Members get Sādhana School workshops included. Enroll: https://enroll.embodiedphilosophy.com/sadhana-school",
    handoff: "They paid separately for a workshop that's included for members (refund)." },
  { id: "A18", topic: "Email", ask: "Too many emails / how do I unsubscribe?",
    answer: "Use the unsubscribe link at the bottom of any email. Right now that unsubscribes them from all marketing emails.",
    handoff: "They want their data deleted entirely." },
  { id: "A19", topic: "Privacy", ask: "Please delete my account and data.",
    answer: "Ichha handles deletion and confirms first, because deletion also removes access to any purchased courses.",
    handoff: "Always: collect email." },
  { id: "A20", topic: "Payments", ask: "My payment didn't go through at checkout.",
    answer: "Try refreshing the checkout page, a different browser, or a different card.",
    handoff: "They were charged but didn't get access." },
  { id: "A21", topic: "Payments", ask: "Why was I charged a different amount in my currency?",
    answer: "Prices are in US dollars, so the bank converts them and may add a fee.",
    handoff: "They ask for a price adjustment." },
  { id: "A22", topic: "Not support", ask: "Podcast guest pitch / journal submission / business offer.",
    answer: "Thank them. Podcast guest ideas go to chitheads@embodiedphilosophy.com; Tarka Journal submissions to tarka@embodiedphilosophy.com. Other business proposals: thank them and say the team has noted it. Do NOT hand these off to Ichha.",
    handoff: "" },
  { id: "A23", topic: "Orders", ask: "Where is my physical order (book or journal)?",
    answer: "Ichha checks shipping. Tarka Journal print copies currently ship within the US only.",
    handoff: "Always: collect order number." },
];

export const HANDOFF_MESSAGE =
  "I've passed this to Ichha on our support team, along with everything you've shared here. She'll reply by email within 2 business days. We're a very small team of 4 people, so we really appreciate your patience.";

export function kbAsText() {
  return KB.map(
    (r) => `[${r.id}] ${r.topic} — Visitor asks: ${r.ask}\nAnswer: ${r.answer}${r.handoff ? `\nHand to Ichha when: ${r.handoff}` : ""}`
  ).join("\n\n");
}
